/**
 * Safety checks shared by the tools that let a worker model touch the disk.
 *
 * These are the difference between delegating I/O and delegating trust. A bad
 * summary wastes a call; a bad write leaves wrong code in the repository, and it
 * is code nobody read. So: an allowlist that keeps generation away from business
 * logic, no silent overwrites, a copy of anything replaced, refusal to emit
 * anything shaped like a credential, and a parser run over the result whose
 * outcome is reported honestly, including when no parser was available.
 *
 * Kept in one place because the two callers must not drift apart on any of it.
 */

import fs from "node:fs/promises"
import path from "node:path"
import os from "node:os"
import { execFile } from "node:child_process"
import { promisify } from "node:util"

const execFileAsync = promisify(execFile)

/** Files whose contents must never be sent to a worker or generated by one. */
export const SECRET_PATHS = [
  /(^|\/)\.env($|\.)/,
  /(^|\/)credentials/i,
  /(^|\/)secrets?($|[._-])/i,
  /(^|\/)service-account/i,
  /\.(pem|key|p12|pfx|jks|keystore)$/i,
  /(^|\/)id_(rsa|dsa|ecdsa|ed25519)$/,
]

/** Values that must not appear in generated content, even as an example. */
export const SECRET_CONTENT = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
  /\bAKIA[0-9A-Z]{16}\b/,
  /\bghp_[A-Za-z0-9]{36}\b/,
  /\bsk-[A-Za-z0-9]{32,}\b/,
  /\bAIza[0-9A-Za-z_-]{35}\b/,
]

/**
 * Paths a worker may create or modify, as globs. Deliberately covers only tests,
 * fixtures and scaffolding: code whose correctness a test run can judge, and
 * whose being wrong does not quietly change what the product does. Widen per
 * repository with "writePaths" or "editPaths" in .opencode/shunt.json.
 */
export const DEFAULT_WRITE_PATHS = [
  "tests/**",
  "test/**",
  "**/tests/**",
  "**/test_*.py",
  "**/*_test.py",
  "**/conftest.py",
  "**/factories.py",
  "**/fixtures/**",
  "**/__fixtures__/**",
  "**/*_test.go",
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/*.test.js",
  "**/*.spec.ts",
  "**/*.spec.tsx",
]

/** Glob subset: "**" spans directories, "*" stays inside one segment. */
export function globToRegExp(pattern: string): RegExp {
  let out = ""
  for (let i = 0; i < pattern.length; i++) {
    const char = pattern[i]
    if (char === "*") {
      if (pattern[i + 1] === "*") {
        // "**/" collapses to an optional prefix so "**/x.py" also matches "x.py".
        if (pattern[i + 2] === "/") {
          out += "(?:.*/)?"
          i += 2
        } else {
          out += ".*"
          i += 1
        }
      } else {
        out += "[^/]*"
      }
    } else if ("\\^$.|?+()[]{}".includes(char)) {
      out += "\\" + char
    } else {
      out += char
    }
  }
  return new RegExp(`^${out}$`)
}

export function isAllowed(displayPath: string, patterns: string[]): boolean {
  return patterns.some((pattern) => globToRegExp(pattern).test(displayPath))
}

export function looksSecret(displayPath: string): boolean {
  const base = path.basename(displayPath)
  return SECRET_PATHS.some((re) => re.test(displayPath) || re.test(base))
}

export function leaksSecret(content: string): boolean {
  return SECRET_CONTENT.some((re) => re.test(content))
}

/**
 * Containment check for a path that need not exist yet, so realpath cannot be
 * applied to the target itself. The nearest existing ancestor is resolved
 * instead, which still defeats a symlink pointing out of the tree.
 */
export async function resolveInside(worktree: string, input: string) {
  if (path.isAbsolute(input)) throw new Error("give a repository-relative path")
  const absolute = path.resolve(worktree, input)
  const realRoot = await fs.realpath(worktree)

  let probe = path.dirname(absolute)
  for (;;) {
    try {
      const real = await fs.realpath(probe)
      if (real !== realRoot && !real.startsWith(realRoot + path.sep)) {
        throw new Error("resolves outside the repository")
      }
      break
    } catch (error: any) {
      if (String(error.message).includes("outside the repository")) throw error
      const parent = path.dirname(probe)
      if (parent === probe) throw new Error("cannot resolve a containing directory")
      probe = parent
    }
  }
  return { absolute, displayPath: path.relative(worktree, absolute) }
}

/** Models wrap output in fences however firmly they are told not to. */
export function stripFences(text: string): string {
  const trimmed = text.trim()
  const match = trimmed.match(/^```[a-zA-Z0-9_+-]*\n([\s\S]*?)\n?```$/)
  return (match ? match[1] : trimmed).replace(/\s+$/, "") + "\n"
}

/**
 * Symbols a file defines. This is what makes a receipt worth trusting: the
 * caller asked for something and can check the names line up, for a few tokens
 * instead of reading the whole body.
 */
export function extractSymbols(text: string): string[] {
  const patterns = [
    /^\s*(?:async\s+)?def\s+([A-Za-z_]\w*)/gm,
    /^\s*class\s+([A-Za-z_]\w*)/gm,
    /^\s*(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_]\w*)/gm,
    /^\s*func\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)/gm,
    /^\s*(?:it|test|describe)\s*\(\s*["'`]([^"'`]{1,60})/gm,
  ]
  const found: string[] = []
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      if (match[1] && !found.includes(match[1])) found.push(match[1])
    }
  }
  return found
}

export type SyntaxCheck = { status: "ok" | "failed" | "skipped"; detail: string }

/** Prefer the repository's own interpreter; a venv may hold the only parser that matters. */
async function pythonBinary(worktree: string): Promise<string | null> {
  for (const candidate of [
    path.join(worktree, ".venv", "bin", "python"),
    path.join(worktree, "venv", "bin", "python"),
  ]) {
    try {
      await fs.access(candidate)
      return candidate
    } catch {
      // Fall through to the interpreter on PATH.
    }
  }
  for (const candidate of ["python3", "python"]) {
    try {
      await execFileAsync(candidate, ["--version"], { timeout: 10_000 })
      return candidate
    } catch {
      // Neither name resolves; the caller reports "skipped".
    }
  }
  return null
}

/**
 * Parse a file we just wrote. Syntax is the cheapest class of bug to catch and
 * by far the most common way generated code fails, so it is worth a subprocess.
 * It proves only that the file parses, which every caller must say out loud.
 */
export async function checkSyntax(worktree: string, absolute: string): Promise<SyntaxCheck> {
  const extension = path.extname(absolute).toLowerCase()

  if (extension === ".py") {
    const binary = await pythonBinary(worktree)
    if (!binary) return { status: "skipped", detail: "no python interpreter found" }
    try {
      // ast.parse leaves no __pycache__ behind, unlike py_compile.
      await execFileAsync(
        binary,
        ["-c", "import ast,sys; ast.parse(open(sys.argv[1]).read(), sys.argv[1])", absolute],
        { timeout: 30_000 },
      )
      return { status: "ok", detail: `parsed by ${path.basename(binary)}` }
    } catch (error: any) {
      const stderr = String(error?.stderr ?? error?.message ?? "")
      const line = stderr.trim().split("\n").filter(Boolean).slice(-3).join(" ")
      return { status: "failed", detail: line.slice(0, 300) }
    }
  }

  if ([".js", ".mjs", ".cjs"].includes(extension)) {
    try {
      await execFileAsync(process.execPath, ["--check", absolute], { timeout: 30_000 })
      return { status: "ok", detail: "parsed by node --check" }
    } catch (error: any) {
      return { status: "failed", detail: String(error?.stderr ?? "").slice(0, 300) }
    }
  }

  if (extension === ".json") {
    try {
      JSON.parse(await fs.readFile(absolute, "utf8"))
      return { status: "ok", detail: "parsed as JSON" }
    } catch (error: any) {
      return { status: "failed", detail: String(error?.message).slice(0, 300) }
    }
  }

  if (extension === ".go") {
    try {
      await execFileAsync("gofmt", ["-e", absolute], { timeout: 30_000 })
      return { status: "ok", detail: "parsed by gofmt" }
    } catch (error: any) {
      const stderr = String(error?.stderr ?? "")
      if (!stderr) return { status: "skipped", detail: "gofmt not available" }
      return { status: "failed", detail: stderr.slice(0, 300) }
    }
  }

  // TypeScript would need the project's own tsc. Saying so beats implying a pass.
  return {
    status: "skipped",
    detail: `no syntax checker wired up for ${extension || "this file type"}`,
  }
}

const SHUNT_DIR = path.join(os.homedir(), ".local", "share", "opencode-shunt")

/** Keep whatever is about to be replaced, so no write is ever final. */
export async function backup(displayPath: string, previous: string): Promise<string | null> {
  try {
    const dir = path.join(SHUNT_DIR, "write-backups")
    await fs.mkdir(dir, { recursive: true })
    const stamp = new Date().toISOString().replace(/[:.]/g, "-")
    const flat = displayPath.replace(/[^A-Za-z0-9_.-]/g, "_")
    const target = path.join(dir, `${stamp}__${flat}`)
    await fs.writeFile(target, previous)
    return target
  } catch {
    return null
  }
}

export async function logTelemetry(entry: Record<string, unknown>) {
  try {
    await fs.mkdir(SHUNT_DIR, { recursive: true })
    await fs.appendFile(
      path.join(SHUNT_DIR, "telemetry.jsonl"),
      JSON.stringify({ ts: new Date().toISOString(), ...entry }) + "\n",
    )
  } catch {
    // Telemetry must never break a tool call.
  }
}

/**
 * Signs that a model shortened a file instead of reproducing it.
 *
 * The most dangerous failure in delegated editing. Asked for a whole file back,
 * models routinely return the parts they touched and a comment where the rest
 * used to be. Since the returned text is written to disk, anything left out is
 * deleted, and it parses fine, so nothing downstream would catch it.
 */
const ABBREVIATION = [
  /^\s*(#|\/\/|\/\*|<!--)?\s*\.\.\.\s*(rest|remainder|unchanged|the rest)/im,
  /(rest|remainder) of (the )?(file|code|content|module)\s+(is\s+)?(unchanged|omitted|the same|as before)/i,
  /^\s*(#|\/\/|\/\*)\s*\.\.\.\s*$/m,
  /^\s*(#|\/\/)\s*\[?(unchanged|no changes?|snip|truncated)\]?\s*$/im,
  /^\s*<!--\s*\.\.\.\s*-->\s*$/m,
]

export function looksAbbreviated(text: string): boolean {
  return ABBREVIATION.some((re) => re.test(text))
}

/**
 * Characters the orchestrator would have emitted to make this same change with
 * search-and-replace, which is what delegating an edit actually saves.
 *
 * Not the size of the diff. An edit tool needs an old string long enough to
 * match uniquely and a new string to replace it with, so every hunk costs its
 * changed lines plus surrounding context, twice over. That is why a one-line
 * change is nearly free to make directly and a hundred scattered one-line
 * changes are not: the context is paid for at each site.
 */
export function searchReplaceCost(diff: string): number {
  let total = 0
  for (const line of diff.split("\n")) {
    if (/^(diff |index |--- |\+\+\+ )/.test(line)) continue
    if (line.startsWith("@@")) {
      // Each hunk needs anchoring context beyond what the diff shows.
      total += 80
      continue
    }
    // Context lines appear in both the old and the new string; changed lines
    // appear in one of them.
    if (line.startsWith(" ")) total += (line.length - 1) * 2
    else if (line.startsWith("+") || line.startsWith("-")) total += line.length - 1
  }
  return total
}

/**
 * Unified diff between two texts, computed here rather than asked of the model.
 *
 * This is the load-bearing decision in delegated editing. The worker returns a
 * whole file and we work out what changed, so it cannot misreport its own edit,
 * and a wholesale rewrite disguised as a small change becomes visible as a large
 * diff. git is used because a correct diff is not worth writing by hand.
 */
export async function unifiedDiff(
  before: string,
  after: string,
  displayPath: string,
): Promise<{
  diff: string
  added: number
  removed: number
  /** Characters of search-and-replace the caller was spared. */
  editCost: number
  available: boolean
}> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "shunt-diff-"))
  const oldPath = path.join(dir, "before")
  const newPath = path.join(dir, "after")
  try {
    await fs.writeFile(oldPath, before)
    await fs.writeFile(newPath, after)
    let stdout = ""
    try {
      const result = await execFileAsync(
        "git",
        ["diff", "--no-index", "--unified=2", "--no-color", "--", oldPath, newPath],
        { timeout: 30_000, maxBuffer: 32 * 1024 * 1024 },
      )
      stdout = result.stdout
    } catch (error: any) {
      // git exits 1 whenever the files differ, which is the expected case.
      if (error?.code === 1 && typeof error.stdout === "string") stdout = error.stdout
      else throw error
    }

    // git prints its own a/ and b/ prefixes, so the temp paths are swapped for
    // the real one bare rather than prefixed again.
    const escape = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    const diff = stdout
      .replace(new RegExp(escape(oldPath), "g"), displayPath)
      .replace(new RegExp(escape(newPath), "g"), displayPath)
    const lines = diff.split("\n")
    return {
      diff,
      added: lines.filter((l) => l.startsWith("+") && !l.startsWith("+++")).length,
      removed: lines.filter((l) => l.startsWith("-") && !l.startsWith("---")).length,
      editCost: searchReplaceCost(diff),
      available: true,
    }
  } catch {
    // Without git, fall back to counts so the caller can still judge the size.
    const beforeLines = before.split("\n")
    const afterLines = after.split("\n")
    const beforeSet = new Set(beforeLines)
    const afterSet = new Set(afterLines)
    const added = afterLines.filter((l) => !beforeSet.has(l)).length
    const removed = beforeLines.filter((l) => !afterSet.has(l)).length
    return {
      diff: "",
      added,
      removed,
      // No hunks to measure, so assume each changed line stood alone: the
      // pessimistic reading, since scattered changes cost more context.
      editCost: (added + removed) * 60,
      available: false,
    }
  } finally {
    await fs.rm(dir, { recursive: true, force: true }).catch(() => {})
  }
}
